### ISSUE TITLE
Online users

### ISSUE THREAD

**Issue by podviaznikov** [hashobject/quizzy#10]
Under learderboard we need to have new panel: "Online users".

It should show users that are currently online.

Should be updated automatically when users joins/leaves app.

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 
We can close that issue. Leaders&Online users works great. 
I'm thinking about how to show ONE question for all users when they login. 

And what tasks are active? As i know: questions generating(right endings of words) and question implementation(show question, take answer and show new answer). yes?

**Comment by podviaznikov** [comment]
yes.
