### ISSUE TITLE
remove dialog on the first page

### ISSUE THREAD

**Issue by podviaznikov** [hashobject/quizzy#12]
That dialog where users should input name doesn't work correctly.

After page reload I need to enter name again.

Remove it and revert to what we had. Let's move in small steps and we will see what UI should be.

**Comment by PodviaznikovPavlo** [comment]
Of course you need to enter name again, because you leave the game. 
Okay, ill revert it.

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 
Wait, but its better in that way. In old version you need always enter your name. But now you enter your name and its all. You can play. In old version you must enter your name, enter message and send it. so it will create new user every time. But there must be one user per one connection. I think this is right. Before starting the game you enter your name and you can play. 

Even if you reload the page, it should ask your name. This is logically correct.

**Comment by podviaznikov** [comment]
I agree that there was problem with previous implementation that you need to enter your name.
But your solution is not good for this situation. There is another way to solve initial problem and we will solve it. Read about html5 `localStorage`. But please revert your change first. That is not final user experience we want to have. We will do separate discussion about what users should see after landing on the site first time.

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 
I remove that dialog

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

you can check master. i have fixed leaders and remove dialog.

**Comment by podviaznikov** [comment]
nice. But it seems that online users are broken now on master
