### ISSUE TITLE
Investigate questions generation

### ISSUE THREAD

**Issue by podviaznikov** [hashobject/quizzy#13]
As discussed we need to think about questions generation.

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov  

okay

**Comment by podviaznikov** [comment]
Don't see links from you yet that you mentioned before about difficulties with implementation.

**Comment by podviaznikov** [comment]
@PavelPodviaznikov ping

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

what?

**Comment by podviaznikov** [comment]
please post links here on your research.

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

1) http://pravopys.kiev.ua/pravopys.aspx?SectionID=2483
2) Родовий відмінок однини іменників чоловічого роду другої відміни - wiki

here are links.

**Comment by podviaznikov** [comment]
this task is still open.

As far as I remember we agreed that you will try to build correct form for some countries.

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

ok, i`ll try to make that(countries) in two days.

**Comment by podviaznikov** [comment]
I have intuition that it should be possible.

E.x. a lot of countries have `я` at the end. And they all should be changed in the same way:

```
Італія - Італії
Іспанія - Іспанії
Бразилія - Бразилії
```

The same with "а" ending.

```
Аргентина - Аргентини
Мексика - Мексики
```

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

with countries there no problems - there are rules, hot to convert to needed form. So i will make it.

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

Well, i make some countries generation. It works. But it works if country name consists of one word. 
Branch - make-right-countries-endings
The result of converting displays in node console. Data is in questions.js, there is array of countries.

**Comment by podviaznikov** [comment]
Didn't check the code but sounds good. So can you generated the whole question now and save it to file and send me file?
By full question I mean "Столиця Італії?".

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 
Yes, i`ll do that.

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

Okay, it is done. Questions about capitals stores in generatedCountries.txt file.

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 
I add json file. It has such structure:
[
  "{\"question\":\"Столиця Німеччини?\",\"answer\":\"Берлін\"}",
  "{\"question\":\"Столиця Австралії?\",\"answer\":\"Канберра\"}",
  "{\"question\":\"Столиця Ірану?\",\"answer\":\"Тегеран\"}",
  "{\"question\":\"Столиця Ісландії?\",\"answer\":\"Рейк'явік\"}"
]

**Comment by podviaznikov** [comment]
Good, but can you don't store wrong questions? Just ignore them.

Send pull request when you are done.

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 
okay. Wrong question is questions, that fail generation, yes? For example countries which consists more than one word.

**Comment by podviaznikov** [comment]
Yes. We want to have just good questions in the final file.

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 
okay

**Comment by podviaznikov** [comment]
Done.
