### ISSUE TITLE
Correct answer improvement

### ISSUE THREAD

**Issue by podviaznikov** [hashobject/quizzy#15]
Right now if answer has uppercase letter in the name the user should type answer also with the uppercase letter.
E.x. if the answer is 'Букет' than both 'букет' should be also acceptable.

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 
yes, i will fix it

is there any bugs that i can fix now?

**Comment by podviaznikov** [comment]
you said multiple times that you have some bug

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

yes, the bug with question sendings. i ask maybe you found something else.

**Comment by podviaznikov** [comment]
No, I didn't. I am not testing much. There are not much functionality, most of the bugs you should be able to find yourself at this point.

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

ok, that all i want to know))

well, there is one bug for that moment(that i see).

**Comment by podviaznikov** [comment]
done.
