### ISSUE TITLE
Working chat

### ISSUE THREAD

**Issue by PodviaznikovPavlo** [hashobject/quizzy#16]
@podviaznikov 

this is chat for us, where we can discuss some things about quizzy

I just want to remind for myself what open tasks i have.

1) Make countries generation.
2) Fix the bug with question sending
3) Fix answers view

Thats all or i forgot something?

**Comment by podviaznikov** [comment]
no need to create task for all of those.

You already have https://github.com/hashobject/quizzy/issues/13 and https://github.com/hashobject/quizzy/issues/15.

Please create concrete task for one feature/bug.
