### ISSUE TITLE
Think about database to use

### ISSUE THREAD

**Issue by podviaznikov** [hashobject/quizzy#25]
We have web app now. It should save some state: users, points etc.

Where do we want to store it? Open for discussion/suggestions.

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

We need database. I remember you was telling about mongoDB. I dont have enough knowledge about databases now. I just remember university course of mysql.

**Comment by podviaznikov** [comment]
I suggest firebase for now.

We would need to store our user's data in the firebase.

Questions we can store either in file (like we are doing now) or in the firebase too. There is nodejs library available: https://www.npmjs.com/package/firebase

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

firebase its good. i like that idea

**Comment by podviaznikov** [comment]
ok, let use firebase
