### ISSUE TITLE
Deploy app to Heroku

### ISSUE THREAD

**Issue by podviaznikov** [hashobject/quizzy#8]
As discussed previously we need to configure Heroku app.

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

I have a question here. As i said, i have deployed chat to heroku, but there appears application errror. What is a question. I am deploying my chat branch, soto heroku goes that brnch, or master branch?

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

So yes, i define what was the problem. Thats because to heroku goes master branch. 
I create new repository, copy there my branches code and deploy to heroku.
Here is a app: https://serene-island-3540.herokuapp.com/

When you merge my branch and master i will deploy our app.

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

I have tested it with my friend on the work. Cool)) it works. This is real chat now))

**Comment by podviaznikov** [comment]
it's possible to deploy any branch to Heroku. Read/find solution. No need to create new repo.

**Comment by podviaznikov** [comment]
@PavelPodviaznikov any progress?

**Comment by PodviaznikovPavlo** [comment]
No, there is error. I deploy my branch, but there is an error. And i dont know whats wrong. Its annoying, because sometimes i deploy on heroku and its all ok, and sometimes it doesnt work. All steps the same.

**Comment by podviaznikov** [comment]
Hard to identify problem when you say that you have error.

At least copy paste your command and error here.

**Comment by podviaznikov** [comment]
close it for now after discussion. don't need heroku.
