### ISSUE TITLE
Questions initial implementation

### ISSUE THREAD

**Issue by podviaznikov** [hashobject/quizzy#9]
1. We should have array of 20 questions/answers on server. Just create array of json objects and hard code questions answers.
2. Any time user open browser page bot should send message "Hello" and send random question.
3. User should type answer to the question and bot should send message "correct" if answer is correct.

All bot functionality should be implemented on the server.

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 
Ok, its clear.

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

Here is a question. "Hello" should be printed every time, when somebody new connected, or just one time?

**Comment by podviaznikov** [comment]
Every time user connected.

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

I need your help before i continue the work.
I need to make refactoring of code, make all possible to make it more readable. 

You gave me some tips about functions and vars names. I have fixed this. 

But i need more tips, how to organize my code. For example, in main.js i have io.('connection') and inside of this many socket.on. Can i fix this?

Can you give me all possible tips that i can reorganize my code, so that it will be more logically.

**Comment by podviaznikov** [comment]
I don't see your changes to functions' names.

I don't know what tips you need and what do you want to do.

Does your code work?

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

leaders, online users, chat works.

**Comment by podviaznikov** [comment]
So, fine for me. If you see some problem with code - refactor it. But I don't know what you want to refactor. There are my code comments that you didn't address yet. At least you didn't push code.

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

Okay. I`ll push all changes.

About questions. I have no ideas how to make it in the right way. I mean, when new user connected, bot sends new question. I have no idea how to fix it. Ideally it should be in that way: user connects, bot send question, another user connects, bot sends the same question and only for that user. Here i have problems.

**Comment by podviaznikov** [comment]
So you have two smaller questions:
1. how to send message just to one user // you can check socket.io docs for that
2. how to send one question to the first user and the same to second after he/she connects // I posted my comment before on this. https://github.com/hashobject/quizzy/pull/14. Didn't have answer from you.

Please answer my comments. Also please keep conversation on the specific topic in one place.

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

yes, i saw that message. 
You say that i should save that question somewhere. I was thinking about that, but i couldnt understand how to use it. I will think more.

**Comment by podviaznikov** [comment]
save current question asked by bot into global variable. When the next users connect take question from global variable instead of generating new one. You are using the same technique for the same problem with online users.

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

I have made that task. Now when you give correct answer, bot send another question. there is one bug. When several users connected, bot send the same question several times. But then, when the answer is correct, bot send only one question.  So it works fine. You can check.

**Comment by podviaznikov** [comment]
I don't understand: this task is done or does it have open bug/problem?

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

It works. But it has open bug. I cant explain it now. If you can - check how it works.

**Comment by podviaznikov** [comment]
I don't understand your response. Can you describe bug that you have?

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

It has one bug. 

When you open two tabs(two players in game) - it works great. But when third player start the game, there appears bug. The bug with questions. Bot sends two diff questions.

**Comment by podviaznikov** [comment]
any idea why it's happening?

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

this is weird, because it works when two players in game. I think i have wrong condition(where i check to send the question or not). i will look at it now.

**Comment by podviaznikov** [comment]
I'm closing this task. Did you fix bug you are talking about above? If not - create issue for it.

**Comment by PodviaznikovPavlo** [comment]
@podviaznikov 

Yes, it works great.

**Comment by podviaznikov** [comment]
Ok. Please create new task in GitHub for this bug and put discussion there.
